/**
 * The implementation of the default ui serializer registry.
 * It used by autogenerated UI to get/apply properties to any Node.
 */
export declare class UIRegistry {
    constructor();
    /**
     * Return instance of the default UIRegistry
     * @returns UIRegistry
     */
    static getInstance(): UIRegistry;
    /**
     * Add serializer
     * @param type type of the serializer
     * @param serializer serializer
     * @returns this
     */
    addSerializer(type: string, serializer: any): this;
    /**
     * Remove serializer
     * @param type type of the serializer
     * @returns this
     */
    removeSerializer(type: string): this;
    /**
     * Return serializer for the specified type
     * @param type serializer for the specified type
     */
    getSerializer(type: string | {
        getClassName: () => string;
    }): any;
}
